language: python
python:
  - "3.7.3"
dist: xenial
branches:
  only:
    - master
install:
  - pip install -r requirements/local.txt
script:
  - cd demo/
  - python manage.py update_geommdb
  - python manage.py test